sudo: false
language: python
python:
    - "2.7"
cache:
    directories:
        - "$HOME/.pip-cache/"
services:
    - redis-server
install:
    - pip install coveralls
    - pip install wheel
    - pip install -r requirements-dev.txt
    - pip install -e .
script:
    - py.test --cov=robby --cov-report=term
after_success:
    - coveralls
deploy:
    provider: pypi
    distributions: sdist bdist_wheel
    user: smn
    password:
        secure: DR3y8NAR41zKVh5b4sJTxlLC/GcBD52cp3EGW7BnAG4tJG+Jyj7h+UWL2o775CMwY0jdvL5GInXG8bB+fOAMbpvlag7EBBplsDlevo7pCgKSISlAQ2kANNbi0qkHEWoNPJAaLHH9ZRTuM6htSShJqsRE95hapgmNrNmAKSFNwPi5MEN9RvSY8fs/U6RvT027j/rjUbJ8vSWFBa0h2AMDv5OTKq7dxUiOieh42CqY12SBRuRshctayXUMnoehRQZD1Lh/0VGYLjRA/g7arR/U0V9PdUqVy0l9Sr7rx+PneSjMfeo82iTgi7VNqQJkbhJbtRFu/UtIGCdzxNwrtplOjhUWh8cRZJ4r15sWsGbEg4mUJZDXtawwzYoM9uzWeoO9S+GQlsLjnjipfVSRVkhfHiWvtJMwgq+LW+OODjBo9OkZ6rGwPNtOXmqdrV1txhoPYXj8H/xVtudM14uEKJwoSOGAiGOrDccp/+rgbh2UYvZpCdylWWLcD/PE771Kyt6Y2fdWrpw8UiMcp5ideP88oBMn6VsotE2tj0NCgZlUVUB4Ku1YbFuNFJz08NxcvTHaVOFZa47nyMB0MR2lcbPJgY04N7v3kxv3htvlIjZv+immq/U9Ks62EnV/W0gbEAdgBk00ws3VXmHrpjSUdTg3q/mo9qX1vXb/INejiQkbvmc=
    on:
        tags: true
        all_branches: true
